package cmd

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/jfjrh2014/nestor/internal/ui"
	"github.com/jfjrh2014/nestor/internal/vcs"
	"github.com/spf13/cobra"
)

// remoteName is the git remote name nestor uses for config sync.
const remoteName = "origin"

// nestorConfigDir returns the nestor config directory path.
// This is where nestor.yml and its git repo live when the user keeps
// their config at ~/.config/nestor/ rather than a local ./nestor.yml.
func nestorConfigDir() (string, error) {
	// If --config points at a file, use that file's directory
	if cfgFile != "" {
		abs, err := filepath.Abs(cfgFile)
		if err != nil {
			return "", err
		}
		return filepath.Dir(abs), nil
	}
	// If a local nestor.yml exists, use cwd
	if _, err := os.Stat("nestor.yml"); err == nil {
		return os.Getwd()
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "nestor"), nil
}

var pushRemoteURL string

var pushCmd = &cobra.Command{
	Use:   "push",
	Short: "Commit and push your nestor config to a git remote",
	Long: `Version-control your nestor config across machines.

Initializes a git repo in your config directory if needed, stages and commits
any changes, then pushes to the configured remote.

Set the remote URL with --remote, or run 'nestor remote add <url>' once.

Examples:
  nestor push --remote https://github.com/you/dotfiles.git
  nestor push            # uses previously configured remote`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runPush(cmd.Context())
	},
}

func init() {
	pushCmd.Flags().StringVar(&pushRemoteURL, "remote", "", "git remote URL to push to")
	rootCmd.AddCommand(pushCmd)
}

func runPush(ctx context.Context) error {
	return runPushOut(ctx, os.Stdout)
}

func runPushOut(ctx context.Context, w io.Writer) error {
	p := ui.New(w)

	if !vcs.HasGit() {
		return fmt.Errorf("git not found on PATH — install git to use config sync")
	}

	dir, err := nestorConfigDir()
	if err != nil {
		return fmt.Errorf("finding config dir: %w", err)
	}

	// Ensure the repo exists
	isNew := !vcs.IsRepo(dir)
	if err := vcs.Init(dir); err != nil {
		return fmt.Errorf("init repo: %w", err)
	}
	if isNew {
		p.OK(fmt.Sprintf("initialized git repo in %s", dir))
	}

	// Configure remote if a URL was provided
	if pushRemoteURL != "" {
		if err := vcs.SetRemote(dir, remoteName, pushRemoteURL); err != nil {
			return fmt.Errorf("setting remote: %w", err)
		}
		p.OK(fmt.Sprintf("remote 'origin' set to %s", pushRemoteURL))
	}

	if !vcs.RemoteSet(dir, remoteName) {
		p.Warn("no remote configured — set one with --remote or 'nestor remote add <url>'")
		p.Info("changes committed locally only")
	}

	// Show what's changing
	staged, modified, untracked, err := vcs.Status(dir)
	if err != nil {
		return fmt.Errorf("checking status: %w", err)
	}
	if staged+modified+untracked == 0 {
		p.Info("nothing to commit, tree is clean")
	} else {
		p.Info(fmt.Sprintf("committing: %d staged, %d modified, %d untracked", staged, modified, untracked))
	}

	// Commit
	if err := vcs.Commit(dir, "nestor: sync config\n\nGenerated by 'nestor push'."); err != nil {
		return fmt.Errorf("commit: %w", err)
	}

	// Push if remote set
	if vcs.RemoteSet(dir, remoteName) {
		p.Info(fmt.Sprintf("pushing to %s ...", vcs.GetRemote(dir, remoteName)))
		if err := vcs.Push(dir, remoteName); err != nil {
			return fmt.Errorf("push (commit succeeded): %w", err)
		}
		p.OK("pushed to remote")
	} else {
		p.OK("committed locally (no remote configured)")
	}

	return nil
}
